logging:
  level:
    org.springframework.data.r2dbc: debug
    web.reactive.function.client.ExchangeFunctions: trace

spring:
  h2:
    console:
      enabled: true

  datasource:
    username:
    password:
    url: r2dbc:h2:mem:templatedb;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    name: templpatedb